### ISSUE TITLE
Can‘t use it in 12 cores 

### ISSUE THREAD

**Issue by ichswarox** [cheneyveron/clover-x79-e5-2670-gtx650#1]
Hi, thanks for your effort,and it works perfect when I disabled 4 cores of 12 cores CPU, but if I activated all cores, my computer won't boot anymore, any solution or suggest?

**Comment by xhyxx25** [comment]
Thank u

**Comment by cqingwang** [comment]
@cheneyveron @xhyxx25  hi,I tried using my own dsdt get from clover and delete 
`Store ("CPUSCK0", CUU0)
Store ("CPUSCK1", CUU1)
Store ("CPUSCK2", CUU2)
Store ("CPUSCK3", CUU3)`
these lines,
 It's work,but usb keybord,usb mouse,and usb bluetooth is not worked

**Comment by cheneyveron** [comment]
add a [USB Patch](https://github.com/cheneyveron/clover-x79-e5-2670-gtx650/blob/91c8a390f3e83a6d5f5755885630fb04391b3392/EFI/CLOVER/config.plist) in Clover ACPI -> Patches.

**Comment by xhyxx25** [comment]
@cheneyveron @cqingwang thanks for your feedback! I will try it again.

**Comment by cqingwang** [comment]
tks,now  is'worked

**Comment by xhyxx25** [comment]
@cqingwang what's your cpu model? mine is 2697v2, if we have same cpu, could you pls provide your efi to me? Thank you!

**Comment by cqingwang** [comment]
@xhyxx25  you can see the link ,is work for me
https://github.com/cheneyveron/clover-x79-e5-2670-gtx650/blob/master/EFI/CLOVER/config-AMD-card.plist
