### ISSUE TITLE
cheneyveron 你好，osx10.12.6卡在苹果进度条不动

### ISSUE THREAD

**Issue by jameszhang18910780315** [cheneyveron/clover-x79-e5-2670-gtx650#10]
我的配置：华南x79大板， e5 2650 ， 16g   ，显卡r5 340x，机械500g，显示器dell p2415q
安装步骤如下：
1、使用你的最新rom【x7946cv.rom】刷主板，使用unibeast 制作u盘【osx 10.12.6】，你提示的主板关闭，和打开项目都以完成。
2、进bios u盘引导，卡在苹果图标进度条一开始的地方，并且不动，我等待了大约10分钟，尝试各种方法均无效。
3、把主板rom刷回原厂x79vt，使用你的第一个版本的efi文件可以安装成功，然后驱动显卡，使用你的变频方法，顺利变频。现在稳定
4、我的问题是，使用你最新的方法，似乎是最好的，但是为什么刷rom后无法安装，可否找到解决方法，我再次尝试安装，谢谢。我的邮箱  maoxin2006@163.com; jameszhang18910780315@yahoo.com; qq 1944015126  期待你的回应，谢谢。

**Comment by cheneyveron** [comment]
刷BIOS以后无法进入安装的话，具体是卡在哪里呢？

**Comment by jameszhang18910780315** [comment]
![img20171030211825_1](https://user-images.githubusercontent.com/33214006/32470424-a5c9d21e-c30c-11e7-8b0a-315d593a4a3a.jpg)

**Comment by jameszhang18910780315** [comment]
这是-v现实的

**Comment by cheneyveron** [comment]
1. 考虑使用OsxAptioFixDrv2代替OsxAptioFixDrv
2. 考虑使用OsxAptioFix2Drv-free2000.efi

**Comment by jameszhang18910780315** [comment]
cheneyveron你好还有个事请教，我的usbwifi。型号tp mn725n vid148f. pid7601 不管如何弄都是驱动不上，请给点建议或者方法，谢谢。

**Comment by cheneyveron** [comment]
usb wifi的型号应该是TP WN725N吧？
先装驱动：http://www.tp-link.com/us/download/TL-WN725N.html
然后插网卡。

**Comment by jameszhang18910780315** [comment]
是的 v1 不是v2
我已经驱动上了，麻烦你了，谢谢。你车子用的如何啊！

**Comment by jameszhang18910780315** [comment]
cheneyveron 我尝试更换如下，故障依旧，不动，还有其他方法解决吗，我发现安装usb wifi后系统开始变慢，而且不稳定。
1、OsxAptioFixDrv2代替OsxAptioFixDrv
2、OsxAptioFix2Drv-free2000.efi

**Comment by cheneyveron** [comment]
如果故障依旧的话，恐怕就是不兼容2.47版本的BIOS了。

**Comment by jameszhang18910780315** [comment]
我现在刷了个bios还不错
下载网址我给你你看看，资源共享！http://x79.apphb.com/mb/#biosDownload <http://x79.apphb.com/mb/#biosDownload>

**Comment by flipphos** [comment]
@jameszhang18910780315  你这个'BIOS是适用于2.47版本的主板吗？
能上传到百度云共享吗？毛子的网页看不懂啊
谢谢！

**Comment by jameszhang18910780315** [comment]
你加我q
