### ISSUE TITLE
没搞明白boot文件应该放在哪里……

### ISSUE THREAD

**Issue by WaterWei** [cheneyveron/clover-x79-e5-2670-gtx650#11]
也是efi分区下面吗？

**Comment by WaterWei** [comment]
就是根目录下那个boot文件

**Comment by cheneyveron** [comment]
1. 确保U盘格式化成了FAT32格式。
2. 我的Repo里有这么几个文件(夹)：

- EFI
- Library
- usr
- boot

3. 下载Repo解压，复制到U盘，确保上面所有的文件夹在U盘根目录里，也就是一进U盘就能看见这些文件(夹)。

**Comment by cheneyveron** [comment]
是的
