### ISSUE TITLE
关于华南3种版型的反馈

### ISSUE THREAD

**Issue by WaterWei** [cheneyveron/clover-x79-e5-2670-gtx650#12]
atx烈焰、atx豪华（2.47）、matx这3个主板我都有，试了一下，sata3的硬盘都是可以完美安装和使用的。
2.47现在bios芯片焊死了，我强刷了一下，出现下面的情况，不知道是刷好了，还是没刷好？系统正常开机启动没有问题。
![_20171101025812](https://user-images.githubusercontent.com/22359927/32243764-4d0a41ae-beb1-11e7-9985-b17a4af275de.jpg)

**Comment by cheneyveron** [comment]
读取相应区域失败，直接退出了，未执行刷操作

**Comment by flipphos** [comment]
@WaterWei
请问，你手上的三块板子都安装黑苹果了吗？哪块成功了，还是都成功了？

**Comment by jameszhang18910780315** [comment]
我手上只有一块，华南x79 2.47 成功了，完美。

**Comment by flipphos** [comment]
谢谢分享成果！

休眠唤醒都正常吗？次数多了会不会造成电脑莫名重启？

2.47不能刷bios吧？只能打补丁实现电源管理？


我准备淘一块2.46的试试看。淘不到再看看2.47。

**Comment by cheneyveron** [comment]
不必要淘2.46的，自己动手用UEFITool提取DSDT，改一下Processor部分和USB部分，然后插入回去即可。

**Comment by flipphos** [comment]
多谢指点！
手上在用z77的黑苹果，也是刷了打了电源管理补丁的bios的，用了几年确实很爽。

下周有空折腾一下华南x79，手上有两块2670闲着也是闲着。

**Comment by jameszhang18910780315** [comment]
这么好，2个2670，牛

**Comment by WaterWei** [comment]
@cheneyveron 其实bios都修改什么内容了，能否分享一下。

**Comment by cheneyveron** [comment]
俺在[文档](https://github.com/cheneyveron/clover-x79-e5-2670-gtx650/blob/master/docs/变更说明-2017-09-30.md#1-对-hnx7946rom-所做的变更)里已经写了。

**Comment by flipphos** [comment]
@WaterWei  请问你的matx板是淘宝上418哪种吗？ 支持reg ecc？是C602芯片的吧？ 能提供一下购买的店名吗？谢谢！

**Comment by zouyanggary** [comment]
@WaterWei 我刷了2.46改版bios后，用群主的驱动无法进入安装界面，请问你是怎么处理的？

**Comment by jameszhang18910780315** [comment]
Cpu型号？
最好不刷bios

**Comment by flipphos** [comment]
我也碰到同样问题，CPU E5 2670 C2
考虑滚回原版bios安装，然后再刷改版bios

> 在 2017年11月21日，07:21，jameszhang18910780315 <notifications@github.com> 写道：
> 
> Cpu型号？
> 最好不刷bios
>

**Comment by jameszhang18910780315** [comment]
不要刷，愿意交流可嘉qq

**Comment by flipphos** [comment]
你qq多少，我加你。



> 在 2017年11月21日，14:06，jameszhang18910780315 <notifications@github.com> 写道：
> 
> 不要刷，愿意交流可嘉qq

**Comment by cheneyveron** [comment]
俺又更新了一下，新的BIOS和EFI可以试试喔。 @jameszhang18910780315  @WaterWei @flipphos 
不刷BIOS的话，变频怎么弄呢？

**Comment by flipphos** [comment]
@cheneyveron 你是说2.47的bios吧？我一早就刷上了。感觉不错啊。你git里面要不要补一个voodoohda
啊？  然后config.plist里面 -v能不能默认关掉？有需要的启动的时候手工打开更方便。

**Comment by cheneyveron** [comment]
git上补上voodoohda啦已经。-v肯定是要默认打开的啦，不然第一次装的时候都不知道怎么调错，配好了没错再关掉

**Comment by Rhenium187** [comment]
话说这个是只有418软妹币的那块板子可以刷吗？烈焰战神行不行0.0

**Comment by flipphos** [comment]
先别刷，尝试用dsdt。刷了锁bios，无法再刷其他bios了。
