### ISSUE TITLE
关于卡nvme硬盘的问题

### ISSUE THREAD

**Issue by WaterWei** [cheneyveron/clover-x79-e5-2670-gtx650#13]
具体表现为，一旦用转接卡+nvme硬盘插到pci-e中，clover进U盘安装，进sata硬盘启动，以及进nvme硬盘都进不去。会表现为下面两种情况。
![_20171101031224](https://user-images.githubusercontent.com/22359927/32244170-a77595ca-beb2-11e7-87a2-2faf7a8103a4.jpg)
![_20171101025823](https://user-images.githubusercontent.com/22359927/32244171-a7ad082a-beb2-11e7-8d0c-656ee116f3b0.jpg)

但是这个版本的efi就不会卡nvme，
[http://bbs.pcbeta.com/forum.php?mod=viewthread&tid=1761123&page=1#pid47728907](url)
这个版本的efi，能安装并进入系统，但因为我不是a卡，即使调整了config的设置，进去后还是驱动不起来。

希望您能帮忙看下，卡nvme的问题是什么原因，我研究尝试了半天，没看到什么特别的设置是解决卡nvme硬盘的。

**Comment by cheneyveron** [comment]
我手头木有NVMe固态，因为有个msata 128的固态 与500G机械 组fusion drive，所以短时间可能也不会升级了，希望同有固态的小伙伴们参与讨论

**Comment by cheneyveron** [comment]
推荐你尝试这么几个操作：
1. 用他的DSDT试试？
2. 用他的KextToPatches试试？
3. 用他的SSDT试试？
4. 用他的Kexts试试？
5. 用他的Drivers64UEFI试试？

**Comment by jameszhang18910780315** [comment]
msata 128的固态 与500G机械 组fusion drive。如果ssd防系统，hdd放文件，这两种有啥区别啊，哪个好？

**Comment by cheneyveron** [comment]
之前只用128的固态放系统，俺用AE和一堆开发工具，很快系统盘就满了。现在628G的系统盘就不用担心满不满的问题了，而且不常用的文件会自动挪到HDD中

**Comment by jameszhang18910780315** [comment]
我想问下，访问速度如何？还有就是如果从新做系统文件会丢失吗？因为fusion drive不是很了解，可否加qq   我的机子是2650，刷bios有些问题。

**Comment by cheneyveron** [comment]
1. 速度很好，平时用就是固态的速度
2. 你不删除，就不会丢。一般新做系统都会重新格式化，那自然会丢文件的

**Comment by jameszhang18910780315** [comment]
非常感谢你的回信，明白了。
> 在 2017年11月5日，06:35，Cheney Veron <notifications@github.com> 写道：
> 
>
