### ISSUE TITLE
安装10.13的时候出现MACH REBOOT

### ISSUE THREAD

**Issue by ngegepdc67** [cheneyveron/clover-x79-e5-2670-gtx650#14]
![c482f8f8e1a41c93f59ffdd4bff37e89](https://user-images.githubusercontent.com/32735771/32449117-b2cd3fde-c34b-11e7-907b-3af891634128.jpg)

**Comment by cheneyveron** [comment]
请使用本Repo的EFI再试
或者在Boot args中勾选 keepsyms=1 和 debug=0x100
