### ISSUE TITLE
安装10.11.6后鼠标键盘没反应？

### ISSUE THREAD

**Issue by ngegepdc67** [cheneyveron/clover-x79-e5-2670-gtx650#16]

**Comment by cheneyveron** [comment]
1. 是USB键鼠吗？
2. 如果USB接口不能用，很可能是DSDT的问题。请参照这里的 ACPI->Patches：
https://github.com/cheneyveron/clover-x79-e5-2670-gtx650/blob/67d0dace2ba8e9592140fcb5a229923c4946a659/EFI/CLOVER/config.plist

**Comment by ngegepdc67** [comment]
是usb
是把https：//github.com/cheneyveron/clover-x79-e5-2670-gtx650/blob/67d0dace2ba8e9592140fcb5a229923c4946a659/EFI/CLOVER/ config.plist里面的内容拷贝到text mode里面吗？

**Comment by cheneyveron** [comment]
只需要参照那个文件改Clover Configurator->ACPI Patches就行了
