### ISSUE TITLE
请问，“对 HNX7946.rom 所做的变更”可以适用于2.47的主板吗？

### ISSUE THREAD

**Issue by flipphos** [cheneyveron/clover-x79-e5-2670-gtx650#18]
您9/30日更新中提到的BIOS更改，是只能用于刷2.46的主板吗？还是也适用2.47的版本？（我是按照主板MSATA口边上显示的版本来区分的）
谢谢！

**Comment by cheneyveron** [comment]
抱歉，不适用2.47版本的，只能用于2.46。
如果有同学提供2.47版本的ROM，我可以抽时间改一下试试：）

**Comment by jameszhang18910780315** [comment]
@cheneyveron.  我手里有所有的2.47版本的bios包括可以超频cpu和内存的，如果可以请尝试帮助修改，另外，你修改后的bios刷好了，整个这个是不是叫ozmosis。如果是可否给些中文的教程或者视频，我发现国外的水平确实高，对ozmosis非常感兴趣，但是受语言限制。如果你愿意改2.47版本，可否加q，我给你发邮件总是失败，不知道为什么q1944015126
