### ISSUE TITLE
各位喜欢hackintosh的朋友，哪位和我的配置差不多，可否交流一下

### ISSUE THREAD

**Issue by jameszhang18910780315** [cheneyveron/clover-x79-e5-2670-gtx650#19]
首先感谢cheneyveron ，提供了很多可用的efi，我的机子使用他较早的efi可以安装成功，但是最近安装了wn725n usb无线网卡，问题就来了，我想可能还是efi没有弄好，我是个小白，希望有和我配置差不多的可以提供一些方法，或者方案，我的主机配置：e5 2650 c2    huanan x79 v2.47    16g 4*4 r5 340x【以驱动】 ，我这个主机无法刷bios，如果刷了，使用最新的efi 不能安装。

**Comment by flipphos** [comment]
网线网卡建议淘一块转接到pcie 1x的苹果原装网卡，94360或者943602系列均可（4或3天线版本）。
插上osx原生支持，省去很多烦恼。

**Comment by jameszhang18910780315** [comment]
感谢！清楚了。
