### ISSUE TITLE
华南X79豪华大板+E5-2660V2进不了安装界面

### ISSUE THREAD

**Issue by zhuxiaoqiao** [cheneyveron/clover-x79-e5-2670-gtx650#2]
大神好，我下载附件安装黑苹果可惜没折腾好，可否留个微信或邮箱联系 @cheneyveron 
谢谢

**Comment by cheneyveron** [comment]
cheneyveron@live.cn
按说现在的EFI应该就可以了。
如果你用的是NVIDIA非免驱卡，那处理器就不能变频啦。
