### ISSUE TITLE
刷新bios后如何用这套EFI进入安装失败

### ISSUE THREAD

**Issue by zouyanggary** [cheneyveron/clover-x79-e5-2670-gtx650#21]
已经刷了bios，使用这套EFI需要对内部文件做什么改动才能正常进入安装呢？Kexts文件夹好像没有10.13这个，config.plist这个需要做点啥变动？主要是刷了主板后，我之前的方案无法进入安装界面了

**Comment by flipphos** [comment]
我也刚刚碰到类似的问题。

@zouyanggary 没有10.13文件夹没有关系，有other就可以。

在之前做好的10.13的CLOVER启动优盘上用git里面的
-     EFI
-     Library
-     usr
-     boot
四个覆盖。
优盘启动显示：

OsxAptioFixDrv: Starting overrides for \.IABootFiles\boot.efi
Using reloc block: no, hibernate wake: no
Error allocating 0x28c pages at 0x0000000003dcc000 alloc type 2
Error loading kernel cache (0x8)
Booting failed, sleeping for 10 seconds before exiting.

我的硬件配置和 @cheneyveron 的一样，刷了CV后缀的BIOS，主板2.46，CPU E5 2670C2，显卡GTX 650 1G。

我将 config-no-web-drive.plist复制为config.plist作为启动配置文件，发现Boot/Default Loader中显示boot.efi
而正是这个boot.efi导致启动失败。
另外根据其他的文章，kext-dev-mode=1 和rootless=0是两个废弃的参数，10.12之后就不再需要了。

另外：9/30日更新日志中说的
drivers64UEFI: 添加了 OsxAptioFix2Drv-free2000.efi 从而 SIP 打开时能启动系统.
并没有放到drivers64UEFI中而在drivers64UEFI_Optional中

**Comment by zouyanggary** [comment]
非常感谢你的指点！我也显示是这行错误。那么这个boot.efi要怎么处理呢？然后把 OsxAptioFix2Drv-free2000.efi 放回drivers64UEFI，去掉kext-dev-mode=1 和rootless=0是两个废弃的参数成功进入了安装界面？

**Comment by flipphos** [comment]
@zouyanggary 惭愧，我也还没有进入安装界面。我手上的优盘带10.13系统和clover，在技嘉主板上装过可用的。 把此优盘上的EFI分区的内容用 @cheneyveron 的git内容替代之后(含上述4个文件夹)，反而出现上述的错误无法进入安装界面了。

现在只能等 CV来指点一下了。

**Comment by zouyanggary** [comment]
上面说的那个boot.efi文件在哪儿文件夹下面？我尝试替换一下

**Comment by cheneyveron** [comment]
@zouyanggary @flipphos 刷新了BIOS以后出现OsxAptioFixDrv问题，之前遇到的是因为2.47版本的主板刷了俺的2.46版本的BIOS，版本不匹配。
俺到12月6号左右有空的时候做一下2.47的BIOS，现在2.47版本的主板先别刷BIOS啦。

**Comment by cheneyveron** [comment]
@flipphos 用OsxAptioFix2Drv-free2000.efi的话可能会导致分配内存的时候卡死，所以后面的更新中俺又换成OsxAptioFix2Drv.efi了。
anyway，你尝试的哪个可以就用哪个：）

**Comment by flipphos** [comment]
@cheneyveron 我还没有机会尝试试用OsxAptioFix2Drv-free2000.efi，明天有空再试试看。我尝试了OsxAptioFixDrv.efi和OsxAptioFix2Drv.efi结果都是出现上述同样的内存分配错误。我和你的主板版本相同，BIOS刷了也是顺利通过。
你的GIT中能放一个2.46的原版BIOS吗？ 万一不行我再刷回原版试试安装。

**Comment by flipphos** [comment]
@cheneyveron EFI分区中的usr文件夹是干嘛用的？按照我其它主板上安装Clover的经验，只需EFI一个文件夹即可。你这里多出usr和library两个文件夹起到了什么作用呢？对于Clover来说应该是不需要这两个额外的文件夹也可以正常启动的。
另外boot文件是非UEFI启动才需要的，你这里是UEFI启动，照理也是可以拿掉的。

**Comment by zouyanggary** [comment]
我这里有加入了nvme组件的2.46和2.47，我刷了2.47后安装很顺利，然后开启sip后自动重启，你要这些bios么？

**Comment by flipphos** [comment]
@zouyanggary 好啊，你能上传到百度云然后分享一个下载链接吗？你说的nvme组件是指插PCIE插槽的那种nvme是吧？ 我正好有块M.2的ssd转接到PCIE上了，可以拿来试验一下。
你昨晚发issue，无法启动的时候用的是2.46的版本？ 然后刷成2.47就顺利安装了？

**Comment by zouyanggary** [comment]
对，就是扩展卡支持nvme，我把启动bios图改成rog了，刷cv的2.46内存分配错误。只有一种情况例外，就是用原版2.46装好，刷bios在换上他的efi可以完美驱动！但是，我刷新这个改版的2.47后用其他人的可以顺利进去安装，cv的efi却无法启动。刷完这个247后，nvme可以自己驱动，但是显示外置，需要patch

**Comment by flipphos** [comment]
你的主板和我一样是2.46吧？（主板上面写着2.46，对吧？）

你刷的改版的2.47顺利吗？刷的时候有没有碰到出错信息？

CV的bios的优点和关键是解锁了msr寄存器，对于实现原生电源管理很重要。

按照你的经验的话，我更倾向与用原版2.46BIOS装好10.13,然后刷bios换上CV的efi。  NVME支持对我来说是次要的。

我已经发了个issue给CV，建议他出一版只解锁了msr寄存器的BIOS，这样兼容性会更好。

**Comment by zouyanggary** [comment]
@cheneyveron好的，我上传个插入nvme组件和rog启动图的2.47你到时候改一下看看，我去做小白鼠

**Comment by flipphos** [comment]
@zouyanggary 启动图插入有什么教程吗？ 到时候有空可以玩玩。
2.46的版本也可以上传一个吗？谢谢！

**Comment by cheneyveron** [comment]
@flipphos @zouyanggary 
1. 使用Clover安装器安装/更新的时候，它除了修改EFI文件夹，还会增加usr、library和boot这三个文件。之前我试着仅仅更新EFI文件夹，Clover的版本并不会更新，所以我后面就全包含进来了。至于具体作用俺也不是很清楚。
2. 原版的BIOS是X7946.ROM，我改过的BIOS是X7946CV.ROM，别混了噢。

**Comment by flipphos** [comment]
@cheneyveron 
1. 你下载的是原版的Clover吗？我用了几年下来都只有一个EFI文件夹的。我安装的时候选了安装到UEFI分区。
boot这个文件我碰到过，安装到非UEFI分区的时候需要依靠这个boot文件来启动。
我看了/usr/standalone/i386下面的文件，都是bootxxx之类的，应该是用于非UEFI启动的，确切地说，是用于MBR分区启动用的。i386下面的txt文件也有类似的说明。应该是过时的文件(夹)了。
我有台黑苹果是通过类似的文件启动的，启动的时候屏幕会闪过一个boot0a之类的字样。因为是从10.8的MBR时代一路升级上来的（现在10.11.x），而且工作正常，就一直懒得去理他。

2. 谢谢你确认bios版本，有助于我区分原版和改版。我在考虑在别的黑苹果上安装一个10.13，然后写入你的EFI挂到华南主板上去。或许也是个捷径，省去切换刷bios了。

3. 做一个只解锁msr寄存器的BIOS吧，剩下的用DSDT搞定即可，更加灵活实用。Future-proof.
实例：我手上的索泰Z77，刷了老外的解锁MSR的bios，从10.8一直用到10.11都巨稳定。休眠唤醒完美。

**Comment by cheneyveron** [comment]
刚才俺自己测试的确实在10.13.1下面无法进入安装界面，现在已经更新了。

**Comment by zouyanggary** [comment]
我已经在imessage上获取了第一手消息了，哈哈。我去试试先，继续反馈
