### ISSUE TITLE
对HNX7946.rom的建议

### ISSUE THREAD

**Issue by flipphos** [cheneyveron/clover-x79-e5-2670-gtx650#22]
@cheneyveron 可以出一个新版的ROM，只解锁 msr 寄存器吗？
因为其它的功能都可以通过DSDT达成，后期改动更加灵活。而msr的解锁对于实现原生电源管理很关键。刷进BIOS是最好的方案。
这样也能最大限度避免我之前碰到的OsxAptioFix2Drv或者OsxAptioFixDrv启动出错的问题。
你如果能发布一个的话我可以马上帮助测试。

**Comment by cheneyveron** [comment]
@flipphos 
1. HNX7946.rom是原版ROM，俺改过的是X7946CV.ROM
2. 俺对ROM中的DSDT仅进行了一些必要的修改，包括修改USB名、处理Processor，这些均是必要的改动——无论你用不用俺的BIOS都必须改这些才行，而且这些改动不大可能引起OsxAptioFixDrv问题。
另外，如果怀疑是内嵌的DSDT有问题，可以手动将你的DSDT放置在ACPI/patched下面，这样即可覆盖内嵌的DSDT。
3. 俺的iMessage是cheneyveron@icloud.com，欢迎交流

**Comment by zouyanggary** [comment]
我刷会你给的原版2.46去玩去了，我在2.47装好了，就是死活都没法驱动GTX950，装了webdriver就开始3分钟自动黑屏重启

**Comment by flipphos** [comment]
2.46原版下一切正常了？

**Comment by zouyanggary** [comment]
我是刷到2.47改版后就没问题。我现在非常迷茫我的这个显卡驱动，当然我也怀疑我主板不正常，因为我插1050就开不了机·····刷会原版后，使用10.12.6的一套EFI什么都不用设置，完美安装后完美进入，但是我驱动不起来GTX950.这是我刚才把bios刷回2.46测试的结果

**Comment by flipphos** [comment]
2.47哪里下载的？我也试试去。。。

**Comment by zouyanggary** [comment]
我现在传给你，691138500加我QQ
