### ISSUE TITLE
你好我是新人，我想問

### ISSUE THREAD

**Issue by jackieleedevelopment** [cheneyveron/clover-x79-e5-2670-gtx650#23]
1) 其實有沒有方法，開VT-d 
2) INTEL 英特尔 2400SC2 這個版可以用嗎？因我是想用兩個 CPU 的。

謝謝

**Comment by cheneyveron** [comment]
1. 在Clover中将dart=0打钩以后，好像VT-d就不用关了。俺自己是没关也正常。
2. 2400SC2这个板子也是X79的，理论上来说是可以的。俺没有这个板子，除非亲自试一试，否则不会知道会有什么问题的。
