### ISSUE TITLE
你好 我想请问一下fusion drive安装10.13的问题

### ISSUE THREAD

**Issue by Zer0xPoint** [cheneyveron/clover-x79-e5-2670-gtx650#24]
现在系统为10.12正常
用官方appstore方法升级10.13重启后出现禁止标志
重启后clover中选择boot os 不能进入系统 也显示禁止标志
但可以用recoveryHD修复并正常进入系统
是否是10.13时磁盘转为apfs clover无法认出所导致？
应该如何解决呢？
thx

**Comment by Zer0xPoint** [comment]
补充一下 在pilst中修改了install osx 和 boot osx 的地址为 boot os x
但clover菜单中只出现boot osx 和 boot Sierra from recovertHD
请问怎么解决没有install osx启动项的问题

**Comment by Zer0xPoint** [comment]
ps.主板2.4.7没有刷bios+2670+gtx670
使用不转换afps安装的方法出现panic

**Comment by cheneyveron** [comment]
1. 使用Recovery HD修复并启动以后，升级到了10.13吗？
2. 如果没有升级，而是重新进入了10.12，那么不要使用App Store的“升级”，另外制作一个High Sierra的启动盘，用-v debug=0x100 keepsyms=1参数启动该启动盘，看看是哪里出错了？

**Comment by cheneyveron** [comment]
另外，现在的High Sierra安装程式在检测到是Fusion Drive之后就不会转换apfs啦，强行转换也会出错的

**Comment by Zer0xPoint** [comment]
准备暂时不更新10.13了 另外现在10.12启动时会黑屏 必须禁用图形加速 gtx670
需要更新lilu吗
thx

**Comment by cheneyveron** [comment]
lilu和NvidiaGraphicFixup都更新一下，然后装上Web Driver即可

**Comment by Zer0xPoint** [comment]
装完web driver依然黑屏 跟用过AGDPfix打补丁有关系吗

**Comment by zouyanggary** [comment]
你用这个干啥呢？不能用这个




------------------ 原始邮件 ------------------
发件人: "Yizhou Li";<notifications@github.com>;
发送时间: 2017年12月16日(星期六) 晚上7:24
收件人: "cheneyveron/clover-x79-e5-2670-gtx650"<clover-x79-e5-2670-gtx650@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>; 
主题: Re: [cheneyveron/clover-x79-e5-2670-gtx650] 你好 我想请问一下fusion drive安装10.13的问题 (#24)




装完web driver依然黑屏 跟用过AGDPfix打补丁有关系吗

**Comment by flipphos** [comment]
是黑屏才需要打AGDPfix这个补丁。

**Comment by Zer0xPoint** [comment]
哈哈是因为之前用的是其他解决方法 就用了补丁
现在准备全新安装10.13
