### ISSUE TITLE
华南至尊烈焰豪华版 e5-1650V2+GTX950+sm951 安装 10.13.2卡得不行

### ISSUE THREAD

**Issue by mastergyp** [cheneyveron/clover-x79-e5-2670-gtx650#25]
我买的是橙色版的华南x79，非常惭愧，到现在还没搞好。不知道是啥问题进到桌面就很卡。想刷bios，一看bios容量是4m的。有其他兄弟这个配置用上了的吗？请帮我看看是哪的问题？

**Comment by mastergyp** [comment]
替换了efi试了下，估计是cpu型号的问题，这u用这包应用各种无响应。

**Comment by wuxushun** [comment]
我是用的这个主板   没有任何问题   就是声卡只能用万能驱动

**Comment by flipphos** [comment]
@wuxushun  可以正常睡眠并唤醒吗？ 睡眠时候风扇都停转吗？  唤醒时有重启现象吗？谢谢！
我在用2.46版的，并不能进入睡眠，其他倒是正常。

**Comment by cheneyveron** [comment]
@flipphos 我测试的在Windows下睡眠时也风扇不停转。Mac下可以进入睡眠，风扇不停转，唤醒不会重启。

**Comment by cheneyveron** [comment]
@wuxushun 你试试AppleALC，我前段时间更新上了

**Comment by flipphos** [comment]
@cheneyveron 你搭配功率计测测看？风扇不停，功率降不下来的。休眠功耗应该在个位数瓦特。风扇不停的时候大约在50w上下，我实测的。50W的功耗，叫休眠不太恰当，叫闲置（空载）功耗还差不多。

**Comment by mastergyp** [comment]
更新一下, bios自己改了下,重新生成ssdt,卡顿没有了,声卡驱动上了,目前的问题就是睡眠风扇还转.

**Comment by yhan219** [comment]
@mastergyp 能够具体说下你怎么改的吗？我这边也是卡的不行
