### ISSUE TITLE
关于非X79芯片组的X79主板卡在apple keystore starting

### ISSUE THREAD

**Issue by 763996076** [cheneyveron/clover-x79-e5-2670-gtx650#27]
替换成我另外一个clover+配置文件成功安装了，但是机型是5.1，如果修改成macpro6.1，则usb全部失效，放了usbinjectall。kext依然无效，目前就差变频就完美了，请问有啥解决思路么？另外，修改过的bios，支持s3状态睡眠么？

**Comment by cheneyveron** [comment]
1. USB不能用： ACPI -> DSDT Patches中，添加 USBE和EUSB重命名为EH01和02的试试试试？
2. 变频看 [这里](https://github.com/cheneyveron/clover-x79-e5-2670-gtx650/blob/master/docs/变更说明.md#22-关于处理器变频)
3. 我也苦恼于只有S1睡眠，在国外OverLockers俄国论坛中有人在华南X79的BIOS中添加了S3状态，帖子在 [这里](https://forums.overclockers.ru/viewtopic.php?t=580210)，但是我的主板不能用他的BIOS，所以暂时也只有S1状态。你可以研究研究。

**Comment by 763996076** [comment]
1,patch这个已经试过了，非常奇怪依旧无法使用，这张x79主板的南桥是b75的，不知道是否有关系

**Comment by 763996076** [comment]
1.patch这个已经试过了，非常奇怪依旧无法使用，这张x79主板的南桥是b75的，不知道是否有关系 
2.X79机型不是必须设置成Mac pro6，1才能睿频么
3.睡眠问题，emmm，我目前已经基本妥协了，每天就只关屏幕不睡眠，每次睡眠我主机就风扇全停还叫不醒

**Comment by 763996076** [comment]
另外，我一台x79芯片组的x79主板用你的efi完美实现了变频等一系列功能，但是usb3实际上只有usb2速度，包括系统显示 最高480m，正常情况？

**Comment by cheneyveron** [comment]
1. 如果Patch以后无法使用，建议你导出BIOS中的DSDT，然后看一下其中的USB设备的名字是什么？一般来说是在_SB\PCI0下。如果不是EUSB和USBE的话，Clover的补丁自然是无法生效的。
2. 机型设置成iMac、Mac Pro、Mac Mini均可变频，关键是在X86PlatformPlugins中注入Mac Mini的变频向量。
3. 我这里能正常使用 USB3.0，不过空闲的时候显示为 USB 3.0 总线 - USB2.0 Hub，速度显示的也是 480Mb/s。插入 Kingston Data Travaler U盘以后就会显示出 5 G/s 的速度，实际复制速度有 20-30 MB/s。换成移动硬盘，有70多MB/s，已经是3.0的速度了。

**Comment by cheneyveron** [comment]
华南使用的芯片组不支持USB 3.0，它是通过外加芯片实现的3.0接口。这就导致默认的BIOS不支持从3.0的接口启动。另外，似乎是只要改了DSDT中的名字系统就能辨认USB口了，并不需要USBInjectAll。

**Comment by 763996076** [comment]
顺便问下 解锁 msr 寄存器具体怎么操作bios，靠补丁毕竟不是很完美，最近手里有编程器想折腾下
