### ISSUE TITLE
E5 2640 x79 gtx760能否安装？

### ISSUE THREAD

**Issue by qinkangdeid** [cheneyveron/clover-x79-e5-2670-gtx650#28]
不知道这个配置能不能装 新手 大侠帮看看
![ludashi](https://user-images.githubusercontent.com/17582522/38198916-3bcb7ee8-36c1-11e8-86a1-faaa02adcdb8.jpg)

**Comment by cheneyveron** [comment]
请尽管尝试，出错了再提问

**Comment by qinkangdeid** [comment]
刷BIOS的时候提示不适用于现有的平台

**Comment by yygutn** [comment]
可以装，。。稳定使用2年了都
