### ISSUE TITLE
Error loading kernel cache (0x9)

### ISSUE THREAD

**Issue by Diaosi1111** [cheneyveron/clover-x79-e5-2670-gtx650#29]
- **系统版本**: 10.13.4

- **BIOS版本**: 2.47

- **主板版本**: 2.47

- **-v图**: 

Error loading kernel cache (0x9)

安装的时候出的错，就选择安装，准备跑码就出错了

**Comment by cheneyveron** [comment]
如果已经安装好了系统，使用过程中出现这个问题，可以试试这么解决：
1. 进入Recovery
2. 点击 工具-终端，打开终端
3. 执行以下命令重建prelinkedkernel （请注意，务必将Macintosh换成你系统分区的名字）：
rm -f /Volumes/Macintosh/System/Library/PrelinkedKernels/prelinkedkernel
touch /Volumes/Macintosh/System/Library/Extensions
kextcache -u /Volumes/Macintosh

如果连Recovery都进不去，那就是EFI中的drivers64UEFI部分配置的有问题了。
