### ISSUE TITLE
USB Clover installation with High Sierra 

### ISSUE THREAD

**Issue by baybaymac** [cheneyveron/clover-x79-e5-2670-gtx650#3]
Hi bro,

Following your instructions with the same motherboard X79 boards with rom flash.  I started with a USB built from my Macbook PRO- High Sierra resulting in an error occurred with clover.  The USB cannot be built at all.  Having checked the USB and learnt that clover was unable to write on the root directory- hidden.  Any hints?

Many thanks.

**Comment by cheneyveron** [comment]
um, if i didn't misunderstand, i believe you're telling me clover itself (at the choosing system interface) cannot recognize your USB port.
If so, that means there's something wrong with your built-in UEFI environment. And, to make sure that's the case, can you use USB mouse or keyboard during start-up or in BIOS?
If you can use USB mouse or keyboard during start-up or in BIOS, but after entering the Installing macOS interface, then the problem may be that you're using an improper DSDT.
If so, try this:

1. flash your ROM back
2. in clover, patch ACPI tables's patch "change EUSB to EH01 and change USBE to EH02" , add droping MATS and BGRT table , Fix_Headers_20000
3. try to boot and see if USB works.

**Comment by cheneyveron** [comment]
One more way to see if there's something wrong with your UEFI environment or DSDT, is that you can try to boot a Windows installer and see if USB works on that install interface( u don't really need to install windows).
Notice that, if you find my DSDT do not fit your motherboard, then we're probably not using the same motherboard, and then you shouldn't use my ROM.
