### ISSUE TITLE
刷BIOS提示说不适用当前的平台

### ISSUE THREAD

**Issue by qinkangdeid** [cheneyveron/clover-x79-e5-2670-gtx650#30]
- **系统版本**: 10.13.4

- **BIOS版本**: 4.6.5

- **主板版本**: v3.41
![11111 _20180417232143](https://user-images.githubusercontent.com/17582522/38879520-20289e92-4296-11e8-850d-4a2dc6dc257f.jpg)
![_20180417232030](https://user-images.githubusercontent.com/17582522/38879449-f416c464-4295-11e8-8bff-1b0c9e5441b5.png)
![1111111111111lud222ashi](https://user-images.githubusercontent.com/17582522/38879475-0432c7d0-4296-11e8-9901-c974f6eccbfe.jpg)
照着教程刷BIOS的时候出现错误  我的版本好像高许多~~~~

**Comment by cheneyveron** [comment]
BIOS版本与主板版本，请开机时按DEL进入BIOS，在界面最下方有。而不是CPU-Z、AIDA或鲁大师中看到的这个“主板版本”。

**Comment by qinkangdeid** [comment]
哦 好 看到了2.17版本 谢谢大神 那么我不刷BIOS也可以刷黑果吗？刷BIOS是说能有好的变频策略？
![img_20180418_230015](https://user-images.githubusercontent.com/17582522/38940293-59fb6aa2-435c-11e8-84ea-bc3d65cc8a43.jpg)

**Comment by tanpengsccd** [comment]
你这是Q65的芯片。。。
