### ISSUE TITLE
fpt无法更新BIOS

### ISSUE THREAD

**Issue by lhliu1982** [cheneyveron/clover-x79-e5-2670-gtx650#32]
Fpt 刷BIOS出错，提示hardware sequencing failed .make sure that you have access to taget flash area
然后用uefipatch给BIOS打补丁，仍然同样错误。

**Comment by lhliu1982** [comment]
Bios 2.47

**Comment by cheneyveron** [comment]
[这里](https://github.com/cheneyveron/clover-x79-e5-2670-gtx650/blob/master/docs/变更说明.md)有说到了，这个BIOS会锁定主板的访问区域，此时只能使用编程器进行刷新喔

**Comment by lhliu1982** [comment]
还没用fpt刷新过rom，可以用fpt吗

**Comment by cheneyveron** [comment]
我猜测，有可能华南后面自己给BIOS加了锁，不允许软件刷新了。
刷新BIOS的时候主板需要临时提高BIOS芯片的电压，这个操作本身就存在烧板子的风险，所以我建议你：

1. 用编程器来写，而不是fpt。
2. 写之前备份一下原来的BIOS芯片内容，防止新BIOS ROM不兼容，旧的也没了。
