### ISSUE TITLE
Intel DX79SR + i7 3960x + GTX980 试了很多都无法进入安装界面

### ISSUE THREAD

**Issue by whidy** [cheneyveron/clover-x79-e5-2670-gtx650#35]
看过无数`pcbeta`, `tonymacx86`, `insanelymac`的相关帖子, 也在google搜了大量的资料, 试过各种Clover组合, 却始终无法启动...

最要命的是, 我开启了-v, 观察每次都是不同的卡住的结果, 完全无法排错...

我的机子配置是

```
Intel DX79SR
i7 3960x
GTX980
DDR3 8G * 2 XMP 2400MHz
```

这么好的主板为啥用的人那么少, 远景里面全是那个什么破华南板, 貌似又不适用= =

我现在有两个版本的OSX, 分别是

* macOS High Sierra 10.13.5(17F77) Installer with Clover 4512
* macOS+High+Sierra+10.13.4+17E199+With+Clover+4423

两个都不行.

不知道有没有人有用过这个主板, 有什么经验分享下. 可以学习学习.

- **-v错误如下**

![image](https://user-images.githubusercontent.com/2074757/42410749-a75496e4-8221-11e8-8504-9ead1b75087c.png)

上面三个箭头表示有时候随机卡在不同的地方.

- **已经采取过而无效的方法**: 

用过该仓的EFI不行, 别人改过的EFI也不行, 我自己笔记本装了黑苹果, 用`MaciASL`修改过这个机子的`DSDT.aml`放在clover的ACPI里面也没作用.

试过`cpus=1`, 试过`npci=0x2000`等等各种命令, 试过nvdisable啥的, 也试过不用web drivers啥的. 都无效

主要是完全不知道现在是卡在什么问题上了...

求指点!

**Comment by flipphos** [comment]
小建议，安装的时候插一块gt640，免驱动的。会让你省事很多。让你能把精力放在别的部件上。
装完一切正常之后，在安装n卡驱动，换上980。

另外，黑苹果不是随便什么主板都能跑起来的，选用别人验证过的兼容主板最好。当然，你能搞定dsdt另说。

**Comment by cheneyveron** [comment]
首先，移除CPUSensors试试？

**Comment by yygutn** [comment]
Intel DX79SR 太贵了, 剑齿虎都没这个贵.....

**Comment by whidy** [comment]
@yygutn 这板子有段时间只卖130美元. 我是千年年底买的时候涨到180美元. 海淘来的..的确有点贵.. 不过intel 绝版的旗舰版主板啊, 我觉得收藏价值挺高的.所以一咬牙就买了.... 没想到用这板子的人那么少- -,,,

**Comment by whidy** [comment]
@cheneyveron 感谢帮助我去找个10.12的试试. 我在geekbench上面看到有的用这个U装了mac, 猜想是不是也是黑苹果, 不过也有10.13.x的~

**Comment by cheneyveron** [comment]
华南的板子也能上这个U，和你的板子没关系的哦

**Comment by whidy** [comment]
@cheneyveron 我下载了一个`macOS Sierra 10.12.6 16G29 Installer with Clover 4123`, 试着用自带的efi启动了一下不成功.

然后试了你推荐的那个EFI， 也是黑屏，查了一晚上，说是可能和显卡驱动有关。

也阅读了，你的项目中的1.3说明，并作了检查

```
1.3 对于NVIDIA显卡
1.3.1 显示器无输出
我在EFI/Clover/kexts/Other中使用了 Lilu.kext 与 NvidiaGraphicsFixup.kext 这俩驱动配合解决“显示器无输出”的问题。你不用任何操作。
```

还是不行。。。

同样的基于该版本的EFI初步尝试了以下几种方案：

* [方案一](https://www.tonymacx86.com/threads/help-gigabyte-z77x-ud5h-replace-geforce-gtx-660ti-by-gtx-1060-how-to-proceed.256013/#post-1776847)：

```
BIOS - Disable Integrated Graphics - PEG as Primary
Use a digital connection to your monitor - VGA is not supported.
Boot with nv_disable=1
Install Nvidia Web Drivers
Config.plist - Do not inject Intel or Nvidia graphics and no ig-platform-id
Edit config.plist - NvidiaWeb = true as per Link
May need to emulate NVRAM - Problem 6 (Install EmuVariableUefi-64 + RC Scripts) or install AptioMemoryFix or OsxAptioFix3Drv
Remove nv_disable=1 from config.plist
MacPro 6,1 or iMac 15 or iMac 17 System Definition need black screen fix as per Link
```

* [方案二](https://www.tonymacx86.com/threads/black-screen-with-macpro-6-1-or-imac-15-or-imac-17-system-definition.183113/)

```
EDIT (03/01/2017):
vit9696 offered a new solution for those who want an easy fix. I haven't tested this but it sounds like it bypasses the offending functionality of Apple Graphics Display Policy. Because it is a separate pair of kexts, it should not require any actions (re-patching) after updates. Install the Lilu.kext & NvidiaGraphicsFixup.kext in /Volumes/EFI/EFI/CLOVER/kexts/Other. It says it's for MacPro6,1 but omrij confirms it works for iMac15 and pastrychef confirms it works for the iMac 17 board IDs as well. 

My last easy solution is a AppleScript app (AGDPfix.app) that patches the OEM kext's info.plist via shell scripts. OS X updates usually cause the kext to be overwritten/updated so the app must be run again after updating OS X, but it's a lot easier than manually patching the info.plist every time. I originally created v1.0 for MacPro6,1 only but have now updated it to v1.1 for use with iMac15/17 sys defs as well. Feel free to download and use the app attached below. NOTE: You will need to use the boot argument kext-dev-mode=1 for 10.10 Yosemite, disable SIP or use kext-dev-mode in 10.11 El Capitan and 10.12 Sierra.
```

* [方案三](http://bbs.pcbeta.com/forum.php?mod=viewthread&tid=1753759)

等等，各种尝试中。。。

目前考虑是不是`SMBIOS`需要更换，或者是其他，每天很忙就晚上研究下。。。

顺便做个记录，明天再看看- -

目前推测10.13那个随机卡屏估计也是显卡有关了= = 。估计所有问题都是显卡问题- -，可惜柜子里躺着一个未知故障的280X， 要是能用就好了😂

**Comment by yygutn** [comment]
200块买一个650试一下,免驱的

**Comment by cheneyveron** [comment]
推荐录制一份-v启动的视频，以便详细观察一下启动过程中出现的问题，黑屏前到底发生了什么？

**Comment by whidy** [comment]
又折腾了一个周末

**好不容易解决了之前卡住不动的问题**，测试了好几个系统版本，分析了好多个各种驱动和kext，总算进入到安装界面了

然而，装到一半就重启了。我先简单说一下怎么解决到了进入安装界面的。

貌似是给予你的那个上面提到的efi修改的，然后各种混合组合，现在已经不知道究竟是个什么版本了。

反正最重要的是`EmuVariableUefi-64.efi`这个文件一定要有，并且不能同时和Lilu和WhatGreen同时存在？

就这样进入到了安装界面，不过-v过程中会提示不支持的cpu什么的，而且进入安装界面前会出现

```
 ioconsoleuser gioscreenlockstate 3...
```

安装到一半，搞了好几次才截到图片。自动重启过程如下：

![image](https://user-images.githubusercontent.com/2074757/43043375-12d0740c-8dc5-11e8-96ec-f8e65e58c6fa.png)
![image](https://user-images.githubusercontent.com/2074757/43043377-1f9804ca-8dc5-11e8-9404-78fa659c3bcf.png)
![image](https://user-images.githubusercontent.com/2074757/43043378-2656a0dc-8dc5-11e8-9125-6c31ee31239d.png)
目前分析还是nvram什么的wen'ti问题吧。还在解决中，又过去了一个星期- -！

**Comment by cheneyveron** [comment]
看起来是BIOS环境下保存环境变量的问题。EmuVariableUefi-64.efi在最新版本的Clover中应该是不需要了，将Clover升级到最新版本，并移除EmuVariableUefi-64.efi再试试？

**Comment by whidy** [comment]
@cheneyveron 又折腾了一周, 才发现陷入误区了... 其实上个错误,无关紧要, 重启选择进入install就好了...

受到该帖的启发<https://www.tonymacx86.com/threads/solved-crash-reboot-on-fresh-high-sierra-install.255254/#post-1770291>

耐心等待安装完毕后如下图

![image](https://user-images.githubusercontent.com/2074757/43361300-19d3e8ae-92fe-11e8-88f9-11e3add53926.png)

还有很多问题(基本上只是进了个系统), webdriver似乎不稳定,有时候黑屏, 同样的clover配置, 用usb启动则可能正常进入, 而系统却黑屏, 并且usb3.0能启动u盘, 却进入系统后无法使用, 很多解决办法还在探索中. 另外图中cpu分数明显不正常. 也在研究中.

再次感谢各位的帮助.

**Comment by whidy** [comment]
非常感谢各位帮助, 实在是太多问题无法解决了, 同样的clover配置有时候启动黑屏有时候不会, ,

用相同的配置 U盘启动则没有问题

USB3.0启动可以,进入mac就无法识别了..

用了shgen那个什么打ssdt的CPU补丁,也没法用, 一直用cpus=1启动,性能无法发挥

还有我的USB蓝牙+WIFI, 驱动也是一直搞不定, 还是放弃了在这个台式机搞了.  关闭啦

再次感谢各位~~~
