### ISSUE TITLE
Can you step by step to make custom DSDT.

### ISSUE THREAD

**Issue by codetay** [cheneyveron/clover-x79-e5-2670-gtx650#37]
Hi cheneyveron,

I know this question so newbie and not concerned with this repo. But i really need your guide about creating custom DSDT. I read many guides about make custom DSDT but both of them are just like apply current patch from rehabman or piker-alpha. But i don't know how to find problem or conflict of current system and how to fix it by the way, which patches need to apply. 

I really interesting in your best work and i hope i can build custom DSDT for my system like you.

Regards.

**Comment by cheneyveron** [comment]
Writing DSDT requires a detailed introduction of the chipsets on board meanwhile understanding of the 
 UEFI specification along with the skill of C programming. This kind of work should be done only by the motherboard manufacture or BIOS makers.
What you need is probably not skills of customizing DSDT, but finding out what and where is the problem that stops macOS from booting, just like I did.
Here's a brief intro of find problems:

1. Try to boot with -v -keepsyms=1 debug=0x100
2. See what's wrong on your screen
3. Some problems are not critical, I would recommend you google for the LAST problem occured that broke your startup progress along with your motherboard / cpu / GPU type.
4. MOST problems do NOT require a DSDT modification. They can be done by modifying your clover configuration or add some kexts
5. If it really needs DSDT modification, then do them according to the instructions
6. If you cannot find anyone came into the same problem or similar problems, it usually means your keywords need to change or shrink. If you find too many similar problems, maybe you should be more specific.
7. If you find only several similar questions and none was answered, you can try to raise a question to some one you think that can solve the problem.

Hope these can help you.

**Comment by codetay** [comment]
Yeahhhhh, thank you very much for your suggestion. Now i know which one to be started first.
