### ISSUE TITLE
新的EFI无法登录系统

### ISSUE THREAD

**Issue by ichswarox** [cheneyveron/clover-x79-e5-2670-gtx650#4]
更新您的新的EFI文件后，提示cpu managerment 错误，请问您还可以分享一下之前的EFI文件吗？

**Comment by cheneyveron** [comment]
点击"Commits"可以看到版本历史，找到你想回到的版本，点最右边的"<>"符号就能进入那个版本了。
另外，AppleIntelCPUPowerManagement.kext错误的话，确保Clover->"kernel and kext patches"里面，"AppleIntelCPUPM"打上勾了
