### ISSUE TITLE
请问是这种华南主板吗？单路，双内存条，MATX主板。

### ISSUE THREAD

**Issue by tanpengsccd** [cheneyveron/clover-x79-e5-2670-gtx650#40]
![img_1470](https://user-images.githubusercontent.com/13959880/46246099-13d27e80-c42b-11e8-9f7d-4d19172d1853.jpg)
（考虑到readme 没法上传图片，只能上图片地址。
但issues 可以直接上传图片的，contributer 可以直接贴出你主板图片）

**Comment by cheneyveron** [comment]
不是MATX版型哦，是ATX，所以咱俩的板子肯定不一样啦

**Comment by tanpengsccd** [comment]
成功了，就差声卡了。2670 有 8档 了

**Comment by cheneyveron** [comment]
试试移除AppleALC和HDAEnabler，放VoodooHDA，应该可以驱动
