### ISSUE TITLE
解锁MSR的脚本为什么执行失败了啊，其他patch也是

### ISSUE THREAD

**Issue by CZY0098** [cheneyveron/clover-x79-e5-2670-gtx650#41]
- **系统版本**: 10.13.4

- **主板版本**: 烈焰战神

-** 执行AICPMPatch.pl 如下：**

AICPMPatch cy$ sudo perl AICPMPatch.pl /System/Library/Extensions/AppleIntelCPUPowerManagement.kext/Contents/MacOS/AppleIntelCPUPowerManagement --patch

/System/Library/Extensions/AppleIntelCPUPowerManagement.kext/Contents/MacOS/AppleIntelCPUPowerManagement

arch: x86_64

_delta: 1
0000000000009393	movl	$0x000000e2,%ecx
0000000000009398	wrmsr

delta: 1
0000000000009446	movl	$0x000000e2,%ecx
000000000000944b	wrmsr

delta: 1
000000000000945c	movl	$0x000000e2,%ecx
0000000000009461	wrmsr

delta: 1
0000000000009572	movl	$0x000000e2,%ecx
0000000000009577	wrmsr

delta: 1
0000000000009e9a	movl	$0x000000e2,%ecx
0000000000009e9f	wrmsr

delta: 1
000000000000a8ff	movl	$0x000000e2,%ecx
000000000000a904	wrmsr

delta: 1
000000000000ad06	movl	$0x000000e2,%ecx
000000000000ad0b	wrmsr

delta: 1
0000000000010704	movl	$0x000000e2,%ecx
0000000000010709	wrmsr

delta: 1
0000000000011b1e	movl	$0x000000e2,%ecx
0000000000011b23	wrmsr

delta: 1
0000000000012c73	movl	$0x000000e2,%ecx
0000000000012c78	wrmsr_

/System/Library/Extensions/AppleIntelCPUPowerManagement.kext/Contents/MacOS/AppleIntelCPUPowerManagement: **Operation not permitted**

**其他patch也都Operation not permitted**

- **已确认clover选上rootless=0，且为了保险，进入恢复模式输入了csrutil disable，但重启后依旧**

**Comment by tanpengsccd** [comment]
把你bios 拿来 我帮你 patch。 你这是 没权限，前面 +  sudo 执行，再输入密码

**Comment by CZY0098** [comment]
> 把你bios 拿来 我帮你 patch。 你这是 没权限，前面 + sudo 执行，再输入密码

我加sudo了啊，看我执行脚本那行，但还是没权限

**Comment by cheneyveron** [comment]
有可能是SIP未关闭，检查一下config.plist

**Comment by cheneyveron** [comment]
没记错的话，rootless=0已经废弃了，果真是：
1. CsrActiveConfig设置为0x67
2. 恢复模式下执行了csrutil disable
3. 当前用户有管理员权限
以上三点都满足了还无法打补丁的话，我也无法提供帮助了，考虑自行提取BIOS ROM然后打补丁吧！

**Comment by cheneyveron** [comment]
自行打补丁的方法也很简单，我写了一篇文章，在[这里](https://www.itmanbu.com/ami-bios-modification.html)

**Comment by CZY0098** [comment]
> 没记错的话，rootless=0已经废弃了，果真是：
> 
> 1. CsrActiveConfig设置为0x67
> 2. 恢复模式下执行了csrutil disable
> 3. 当前用户有管理员权限
>    以上三点都满足了还无法打补丁的话，我也无法提供帮助了，考虑自行提取BIOS ROM然后打补丁吧！

抱着试试的心态重新装了一遍居然就patch成功了，clover在上次基础上没做任何改动，不明白为什么会这样，但是算是解决了！谢谢！
