### ISSUE TITLE
完美安装后2670更换1650导致进不去系统

### ISSUE THREAD

**Issue by 763996076** [cheneyveron/clover-x79-e5-2670-gtx650#43]
## 提问模板

- **系统版本**: 10.14

- **BIOS版本**: 2.47

- **主板版本**: 2.46

- **-v图**: 

【假装有图片】

- **已经采取过而无效的方法**: 
 蜜汁问题，使用这一套配置，2670+7850的配合完美装上了mojave，包括变频等，当我把CPU更换为1650时，进不去系统，卡在-v之后进入白苹果读条界面100%的状态。2670已经卖了，没法换回来测试。
尝试再次安装，安装时，进安装盘-v之后读条，大概率会卡在读条一半的位置，但是有鼠标，此时拔插视频线就可以进入安装界面（神奇）。但是安装完之后系统非常卡，而且重启大概率也会出现卡在-v之后白苹果进度条满的情况

**Comment by cheneyveron** [comment]
1. 首先试试cpus=1，单线程能否正常启动？
2. 是否正确修改VoodooTSync中的线程数？
3. 是否替换ssdt为1650的ssdt？

**Comment by Jray616** [comment]
@763996076 老哥你问题解决了吗，我也是1650 遇到了跟你一样的问题

**Comment by 763996076** [comment]
> @763996076 老哥你问题解决了吗，我也是1650 遇到了跟你一样的问题

参考2楼的解决方案完美解决，主要是在windows下用记事本修改VoodooTSync.kext的话这个kext大概率会失效，去tonymacx86下载一个用

**Comment by Jray616** [comment]
@763996076 能否发一份你的EFI ？我配置跟你这个应该基本一样。 十分感谢

**Comment by 763996076** [comment]
> @763996076 能否发一份你的EFI ？我配置跟你这个应该基本一样。 十分感谢 [624397346@qq.com](mailto:624397346@qq.com)

已经换机了，用楼主的efi应该是完全ok的，只需要
换成6核心的VoodooTSync
替换ssdt为1650的ssdt
可以再windows下进行，如果单系统，可以用cpus=1先安装

**Comment by Jray616** [comment]
@763996076 cpus=1 是什么意思欸？单核心？ 那照上面说的改好之后，后面需要改回来吗？
