### ISSUE TITLE
什么是NVIDIA Web Driver，我装Windows系统的时候都是自动安装的驱动，没有专门安装过Nvidia的驱动。

### ISSUE THREAD

**Issue by smcdl** [cheneyveron/clover-x79-e5-2670-gtx650#46]
对NVIDIA Web Driver不太了解，有明白的可以帮忙解答一下。

**Comment by cheneyveron** [comment]
所有的操作系统都需要使用驱动来识别和使用硬件。
在Windows系列系统中，只有Windows 10系统可以自动安装驱动，此前版本的Windows也都是需要手动下载NVIDIA的驱动安装好以后才能正确的识别和利用显卡进行加速。
NVIDIA Web Driver是NVIDIA制作的用于帮助macOS和OS X识别和利用NVIDIA显卡进行加速的驱动软件。
可以在下面的地址下载：

- https://www.tonymacx86.com/nvidia-drivers/
- https://www.insanelymac.com/forum/topic/324195-nvidia-web-driver-updates-for-macos-high-sierra-update-08302018/
