### ISSUE TITLE
对于烧录BIOS那步没搞明白，是说要自己买个BIOS芯片烧录已提供的BIOS ROM，然后替换主板上的BIOS芯片吗？

### ISSUE THREAD

**Issue by smcdl** [cheneyveron/clover-x79-e5-2670-gtx650#47]
关键主板上的BIOS芯片是可插拔的吗？

**Comment by cheneyveron** [comment]
刷写BIOS可能造成无法修复的问题，修改BIOS和刷新BIOS的方法众多，不在本Repo讨论的范围内，请自行Google。

请注意，刷写前务必备份原BIOS，并确保手上有一个编程器和另一台可工作的电脑。

刷写方法至少有以下：

1. 主板带的刷新程序
2. AMI提供的工具
3. BIOS自身
4. 编程器
