### ISSUE TITLE
大佬 我也是e5 2670  我这个配置能安装黑苹果吗?

### ISSUE THREAD

**Issue by badboy-tian** [cheneyveron/clover-x79-e5-2670-gtx650#5]
![kwa j cc o c9 jeei43l](https://user-images.githubusercontent.com/2835129/31481332-5c1ccbe6-af55-11e7-962c-d2c59c54604b.jpg)

**Comment by tianqiujie** [comment]
付费安装也行  有联系方式吗

**Comment by tianqiujie** [comment]
![img_20171012_141732](https://user-images.githubusercontent.com/2835129/31482738-09a25d84-af5c-11e7-8031-472ba190c293.jpg)
直接放你的efi 出现这个问题

**Comment by cheneyveron** [comment]
抱歉，这几日十分忙碌... 会一直持续到22号。我的邮箱是cheneyveron#live.cn
clover configurator中boot勾选keepsyms=1和debug=0x10以后还是这样的界面吗？

**Comment by tianqiujie** [comment]
我换了个显卡 买了个GTX 1050TI 不知道能行不

**Comment by tanpengsccd** [comment]
华硕的板子听道格说更完美。
