### ISSUE TITLE
免驱网卡（带蓝牙），网卡正常使用，蓝牙无法识别

### ISSUE THREAD

**Issue by XiaofengYue** [cheneyveron/clover-x79-e5-2670-gtx650#50]
## 提问模板

- **系统版本**: 10.13.6

- **BIOS版本**: 2.47

- **主板版本**: 2.46

你好，我想请问一下，我使用了BCM94360网卡（带蓝牙）。
网卡正常使用，然后蓝牙无法识别到。因为蓝牙走USB。怀疑是USB的问题。然后并不太清楚如何更改。
我该怎么做，或者有什么参考网页吗？谢谢

【假装有图片】

- **已经采取过而无效的方法**: 

查看了别人的USB改动方法，发现并不太一样
这是我测试USB接口的详情
<img width="555" alt="2019-01-01 17 03 24" src="https://user-images.githubusercontent.com/28940374/50571499-2ae88a00-0de7-11e9-8441-d738bce099a1.png">

**Comment by cheneyveron** [comment]
抱歉，刚才看到。我手头正巧有BCM94360CS2和BCM943602CS，可以探讨一下：
BCM94360系列网卡PCI转接卡一般是分成两个通道，其中：

1. WiFi走PCI通道
2. 蓝牙走USB通道

并且有的转接卡挑PCI通道，所以可能得挨个的试主板上的接口。
蓝牙有可能也会挑，主板上一般有两个USB2.0的针脚，你可以挨个试试。

一般来说，不需要动USB接口的映射。你可以先在Windows下试试是否可识别到蓝牙，然后重启回macOS。
如果Windows下，主板上的两个针脚也不能用，有可能是转接卡有问题，或者兼容性问题了。
