### ISSUE TITLE
兄台博客的SSL证书已过期

### ISSUE THREAD

**Issue by YIN-Renlong** [cheneyveron/clover-x79-e5-2670-gtx650#51]
建议更新证书，并添加letsencrypt的自动更新功能。

**Comment by cheneyveron** [comment]
感谢提醒，此前设置了自动更新来着，我去检查一下 :)

**Comment by YIN-Renlong** [comment]
用你的配置文件成功在戴尔 Precision T3610 (C602/X79) 引导10.13.5 （CCC备份的系统）。
处理器是 Xeon 1607 v2，但 DSDT 用的是你配置完毕的 Xeon 1620 v2，正常进入系统。

特此感谢！

**Comment by cheneyveron** [comment]
恭喜呀。
现在正在被Ryzen搞得焦头烂额中，不得不说，民用主板对虚拟化技术的支持还很不成熟，坑多得很。
我微信是cheneyveron

**Comment by YIN-Renlong** [comment]
感谢！这是我第一次在戴尔的机器上折腾这个系统，对 AMD 的系统就更无发言权了。

现在暂时的问题是：处理器总是保持最高频率 (Intel Power Gadget) 中 （正常情况下会频率上下波动）。如果兄台有思路和类似的解决方案，还望请教。

平时用邮件较多，不过等我回去即加微信，再交流请教。

再次祝好！

**Comment by YIN-Renlong** [comment]
重新配置了ssdtPRGen ，并加上了我的CPU具体清单。现在CPU的电源管理功能正常。

还有其他小问题要修修补补，例如在开机会看到Overcurrent （USB 口电流过载）等等问题。

我们再交流。
