### ISSUE TITLE
新手相关问题

### ISSUE THREAD

**Issue by nilhy** [cheneyveron/clover-x79-e5-2670-gtx650#52]
#### 问题如下

初来乍到， 听说10.14不支持N卡， 我想问的是如果我这配置装macOS10.13.6 可行吗？ 

#### 电脑配置如下： 
电脑型号		兼容电脑台式机    
处理器			Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz
内存容量		24.0GB
显卡			NVIDIA GeForce GTX 1050
硬盘			faspeed K5-240G SCSI Disk Device (240GB)
主板			X79
网卡			1、Realtek PCIe GbE Family Controller
			2、Remote NDIS based Internet Sharing Device
声卡			1、NVIDIA High Definition Audio
			2、Realtek High Definition Audio
显示器			240RS  分辨率:1366x768 
当前操作系统		Windows 7 64位

**Comment by cheneyveron** [comment]
最重要的信息是主板厂商及型号你给漏了。
不过，目测可行。
