### ISSUE TITLE
下载最新版本，clover版本号没变，进入clover 没有安装选项

### ISSUE THREAD

**Issue by Jray616** [cheneyveron/clover-x79-e5-2670-gtx650#53]
## 提问模板

- **系统版本**: 10.14.4

- **BIOS版本**: 2.47

- **主板版本**: 2.46

- **-v图**: 

【假装有图片】

- **已经采取过而无效的方法**: 
下载昨天更新的最新版本，clover版本号没变，进入clover 没有安装选项

**Comment by cheneyveron** [comment]
非常抱歉，因现在X79的机器放在家里了，手头无机器，难以测试，今天与网友交流后发现是efi/boot/bootx64.efi漏更新了的缘故。

目前发现两个问题：

1. 在最新的10.13.6下应该还存在nvme驱动bug的问题。
2. Clover的版本未更新。

今天热心网友**Will.i.am**资助了一块烈焰x79主板，5月1号之前应该就能到货，届时我再一并更新与修复。

再次抱歉，在此之前，请朋友们先别更新。

**Comment by cheneyveron** [comment]
我的微信是 cheneyveron ，如有兴趣交流，可加我

**Comment by cheneyveron** [comment]
已经更新，请试试新的EFI吧：）
