### ISSUE TITLE
我的主板也是华南烈焰橙色大板，能分享一下主板的ROM吗？

### ISSUE THREAD

**Issue by blankhub** [cheneyveron/clover-x79-e5-2670-gtx650#56]
之前刷了其他版本丢失了原厂BIOS，无法S3深度休眠

华南烈焰橙色大板，能分享一下主板的ROM吗？

**Comment by cheneyveron** [comment]
再次提醒诸位，所有的刷BIOS的工具都会带备份的功能，所以刷之前务必 **_先备份_** ！

华南几乎全系列的BIOS都在这里：

https://xeon-e5450.ru/socket-2011/motherboards/bios-dlya-huanan-x79-deluxe/

和

http://x79.apphb.com/mb/

这两个地方。

要注意，华南陆陆续续出了很多型号，光是烈焰战神就经历了三个版本：

1. g279k ver13
2. g279k ver14 ，与 G279T v6.0 其实一样
3. G279T V6.11

关于以上三个版本的优劣势与BIOS的兼容性介绍在 [这里](https://xeon-e5450.ru/socket-2011/motherboards/huanan-x79-deluxe-gaming-series/)。简单来说：

1. G279T V6.11可以使用G279T v6.0的BIOS
2. 其他板子都不要使用其他板子的BIOS

**Comment by cheneyveron** [comment]
另外，自己主板的版本印在CPU插槽下方。这里的字样才是最准确的。

**Comment by blankhub** [comment]
谢谢分享，我的主板上印着G279T V6.11

**Comment by cheneyveron** [comment]
那就推荐你用这个 `G279T v6.0_mod_cpu_ram.bin`

**Comment by blankhub** [comment]
谢谢
