### ISSUE TITLE
华南X79豪华标准板+ E5-2660 显卡hd7850升级到10.12 cpu一直在满载运行

### ISSUE THREAD

**Issue by ngegepdc67** [cheneyveron/clover-x79-e5-2670-gtx650#6]
华南X79豪华标准板+ E5-2660显卡hd7850升级到10.12 cpu一直在满载运行 ，显卡型号不能正常识别。

**Comment by cheneyveron** [comment]
cpu变频问题看文档说明，没有刷新bios的话就需要手动解锁msr补丁、给AICPM.kext打补丁了，具体就是运行for-old-rom里面的那几个文件

**Comment by ngegepdc67** [comment]
10.11的时候没做变频就一个档位正常。

**Comment by ngegepdc67** [comment]
具体怎么操作

**Comment by cheneyveron** [comment]
CPU变频的中文说明在这里：https://github.com/cheneyveron/clover-x79-e5-2670-gtx650/blob/master/docs/读我.md#cpu-e5-2670-v1-c2
所有X79平台变频教程的祖宗在这：http://www.insanelymac.com/forum/topic/324270-sandy-bridge-e-ivy-bridge-e-power-management-1013-dp/

**Comment by ngegepdc67** [comment]
我cpu2660主频2.2需要变频吗？我现在用的efi就一个档位，任务多的时候瓦数升高，平时低功率运行，用大神这个一个档位一直高功率运行不知道怎么回事？

**Comment by cheneyveron** [comment]
需要。要变频的话，你需要有自己的SSDT才行。
1. 到rampage.dev上下载X79包，里面有用于2660的ssdt。
2. 这个文件是Yosemit - High Sierra都通用的。
3. 放到patched里面和dsdt放一起。
4. 把kexts里面的CPUFriend和CPUFriendProvider都删掉。这两个文件会注入2670的变频向量。

**Comment by ngegepdc67** [comment]
能帮我配置一个10.13 的efi吗？试了好几次没成功

**Comment by ngegepdc67** [comment]
能帮我配置一个10.13的efi吗？试了好几次没成功，邮箱：ngegepdc67@gmail.com

**Comment by ngegepdc67** [comment]
rampage.dev打不开

**Comment by cheneyveron** [comment]
抱歉，正确网址是这个：http://www.rampagedev.com/downloads/x79-dmg-2/
我现在用的efi就在Code中，所以如果你不能用的话，参照我解决问题的思路一点点分析即可。我没有摸到你的硬件，难以帮你配置efi。

**Comment by ngegepdc67** [comment]
10.11怎么运行这个AICPMPatch.pl文件？

**Comment by cheneyveron** [comment]
10.11运行这里的：https://github.com/cheneyveron/clover-x79-e5-2670-gtx650/tree/master/attachments/frequency/10.11

**Comment by cheneyveron** [comment]
运行方法也在里面写着的，两个命令，一个是检测，另一个是打补丁

**Comment by ngegepdc67** [comment]
没刷主板需要把dsdt放到补丁里面吗？

**Comment by cheneyveron** [comment]
是的。请阅读repo中的更新指南和说明。
