### ISSUE TITLE
Realtek ALC892

### ISSUE THREAD

**Issue by k0ttee** [cheneyveron/clover-x79-e5-2670-gtx650#61]
VoodooHDA works, but the sound quality is poor :(
Is it possible to make sound work using AppleALC.kext for Realtek ALC892?

**Comment by cheneyveron** [comment]
Yes. ALC892 is supported by AppleALC, see [here](https://github.com/acidanthera/AppleALC/tree/master/Resources/ALC892).
For installation, follow the instructions [here](https://github.com/acidanthera/AppleALC/wiki/Installation-and-usage)
