### ISSUE TITLE
准备攒台机器，这个配置能行不

### ISSUE THREAD

**Issue by xdmdpz** [cheneyveron/clover-x79-e5-2670-gtx650#62]
### 我要干啥

准备攒台主机，突然发现了这个库

### 这整机器用来干啥

主要用来做做视频修修图写写代码

会用到Docker for Mac

以前黑过一台i7 8700+1060的主机，第一次用X79

### 我有啥问题

1. 是否还需要刷bios
2. 是否可以直接用您的EFI和官方镜像进行安装
3. 若是可以，目前这个配置推荐哪个版本的系统
4. 安装时有没有什么需要注意

下面是我的配置
- 主板：烈焰橙色大板
  > 548那个，我需要3个PCIE的口

- CPU：e5-2696v2
  > 在`attachments/SSDT-1`找的型号 

- 显卡：AMD蓝宝石RX590 8G
  > 这个应该免驱吧

- 网卡： X520-SR2 （拆机的）
  >  据说可以连NAS剪4K

- 声卡：这个不太懂
  >  主板上的可以直接用吗

**Comment by cheneyveron** [comment]
1. 需要刷BIOS来解锁MSR寄存器，见[这里](https://www.itmanbu.com/ami-bios-modification.html)
2. 可以
3. 10.12.0 - 10.15 喜欢哪个就选哪个
4. 无

**Comment by xdmdpz** [comment]
刷MSR的那些命令，直接在windows命令行执行 就可以吗

**Comment by xdmdpz** [comment]
这里找rom 然后用patch解锁 直接刷入就行吗
https://xeon-e5450.ru/socket-2011/motherboards/bios-dlya-huanan-x79-deluxe/
http://x79.apphb.com/mb/
