### ISSUE TITLE
刷完bios后的感想...

### ISSUE THREAD

**Issue by j1ans** [cheneyveron/clover-x79-e5-2670-gtx650#63]
本人华南大版2.46 刷入未解锁cpu 内存的 bios 后期更换的logo根本没有 妹反应 而且似乎我如果插第二个sata设备（刻录机、硬盘）就打不开电脑似乎 Windows pe也进不去 刻录的macOS10.13.5对于588进去安装就花屏似乎 用了amd plist文件 所以也没安装 非必要需求的建议别刷bios了
![78192C54-5146-4017-A701-9B193D94B3AC](https://user-images.githubusercontent.com/40492732/64915699-a89acd00-d79f-11e9-8320-8f2b382d264c.jpeg)

**Comment by j1ans** [comment]
还是感谢作者的付出 这里提醒一哈小伙伴们

**Comment by cheneyveron** [comment]
谢谢反馈。
寨版的bios和主板变动频繁，因此最好是自己提取bios，解锁msr以后刷入。

在 2019年9月15日，上午10:01，j1ans <notifications@github.com<mailto:notifications@github.com>> 写道：


还是感谢作者的付出 这里提醒一哈小伙伴们

**Comment by j1ans** [comment]
对了 之前我提取过2.46的bios 根本没有logo图像 所以某些版本的2.46应该是也不能通刷的 bios不一样 我是2016年买的
