### ISSUE TITLE
请教:关于是否需要进行1.2.2步骤的疑问

### ISSUE THREAD

**Issue by xinyangmaojian** [cheneyveron/clover-x79-e5-2670-gtx650#68]
## 提问模板

- **系统版本**: 10.15.1

- **BIOS版本**: 未知

- **主板版本**: 未知（型号是华南x79-zd3）

- **-v图**: 

大佬你好：
我已经用你最新版本的efi成功安装上了10.15.1的版本。先在此表示感谢。
目前使用的第一天，还在适应，暂未发现什么不妥，但是我的CPU是2696 v2，本人小白，不是很确定下图中两步是否需要执行？因为我安装的时候没找到attachments文件夹在哪，所以就忽略果去了。
暂时就这一个问题，麻烦大佬了。
![image](https://user-images.githubusercontent.com/26449547/76158148-a6616c00-614d-11ea-8d4e-b825a8a47212.png)

**Comment by xinyangmaojian** [comment]
感谢华南x79的efi请大佬吃个冰淇淋

**Comment by cheneyveron** [comment]
repo里没准备10.15系列的aicpm补丁。所以
上面那个1.2.2最好别执行。

下面那个是需要的，换成自己处理器的voodootscsync.kext与ssdt

**Comment by xinyangmaojian** [comment]
> repo里没准备10.15系列的aicpm补丁。所以 上面那个1.2.2最好别执行。 下面那个是需要的，换成自己处理器的voodootscsync.kext与ssdt

好的  反正1.2.2那个我也没找到地方   感谢大佬。
