### ISSUE TITLE
C602双路E5-2670变频失败

### ISSUE THREAD

**Issue by BrushXue** [cheneyveron/clover-x79-e5-2670-gtx650#69]
- **系统版本**: 10.15.4

- **BIOS版本**: N/A

- **主板版本**: Asrock EP2C602 E5-2670*2

您好：我的黑苹果完成度99%，只差CPU变频。尝试直接使用您的SSDT.aml和CPUFriend，变频无效。目前SMBIOS设置为MacPro6,1 ，是否一定要改成和你相同的iMacPro1,1？谢谢！

**Comment by cheneyveron** [comment]
是否已经解锁了MSR寄存器？

**Comment by BrushXue** [comment]
已解锁
```
 - I/O MWAIT Redirection Enable......... : 1 (enabled, IO read of MSR(0xE4) mapped to MWAIT)
 - CFG Lock............................. : 0 (MSR not locked)
 - C3 State Auto Demotion............... : 1 (enabled)
 - C1 State Auto Demotion............... : 1 (enabled)
 - C3 State Undemotion.................. : 1 (enabled)
 - C1 State Undemotion.................. : 1 (enabled)
 - Package C-State Auto Demotion........ : 0 (disabled/unsupported)
 - Package C-State Undemotion........... : 0 (disabled/unsupported)
```
我只复制了'ACPI/patched/SSDT.aml'，'kexts/Other/CPUFriend.kext'和'kexts/Other/CPUFriendDataProvider.kext'，Clover补丁参考https://www.insanelymac.com/forum/topic/324270-sandy-bridge-e-ivy-bridge-e-power-management-1013-appstore-release/?do=findComment&comment=2698877 ，没有做其他与CPU有关的改动。

**Comment by BrushXue** [comment]
我把我的EFI文件夹发出来以供研究
https://github.com/BrushXue/EP2C602-4LD16-E5-2670-Hackintosh
您能否分享这些（E5-2670，10.15）：
1. Clover中的AICPM补丁（Sandy Bridge）
2. ssdtPRGen所用到的参数
3. CPUFriendDataProvider所用到的参数
谢谢！

**Comment by BrushXue** [comment]
更换为IVB-E处理器，问题解决。
