### ISSUE TITLE
在安装界面出现禁止标志并花屏

### ISSUE THREAD

**Issue by biologystudy** [cheneyveron/clover-x79-e5-2670-gtx650#70]
- **系统版本**: 10.13.6

- **BIOS版本**: 3.41

- **主板版本**: x79-6m

- **-v图**: 主板图
![20200501175737](https://user-images.githubusercontent.com/45864095/80797931-a625a000-8bd5-11ea-9b35-c1249553207f.png)

在加载完这个界面后就出现禁止标志并花屏，字体全模糊了，所以放上此图，出现禁止标志并花屏时候最后一行显示waiting boot啥的
![20200501175748](https://user-images.githubusercontent.com/45864095/80798282-a4101100-8bd6-11ea-8655-1cba9a6ca067.jpg)

- **已经采取过而无效的方法**: 
-1.尝试过替换usb口，全部，全部口都试过都是一样的问题
-2.怀疑是显卡驱动问题，尝试在clover启动里面加入nv_disable=1，结果无效
-3.根据网络方法替换两个kexts：http://bbs.pcbeta.com/forum.php?mod=viewthread&tid=1688071&page=1#pid45909594  结果无效
-求大神救救我呀

**Comment by useafterfree** [comment]
Make sure to use either FakeSMC or VirtualSMC

**Comment by cheneyveron** [comment]
> Make sure to use either FakeSMC or VirtualSMC

Looks like he's using FakeSMC v6.26.

I guess it has something to do with the USB port cuz that device related to boot-uuid cannot be found. However he tried switching usb ports and using usbinjectall.kext and GenericUSBXHCI.kext. Maybe the kexts are not at the right place?

**Comment by useafterfree** [comment]
I see FakeSMC and SMCSuperIO which is a VirtualSMC plugin, which means he is likely using both

**Comment by cheneyveron** [comment]
Yea i missed that. This's a good point.

**Comment by biologystudy** [comment]
> Make sure to use either FakeSMC or VirtualSMC

I dont know what are FakeSMC or VirtualSMC, where are ？If you are convenient tell me ,please.

**Comment by cheneyveron** [comment]
> I dont know what are FakeSMC or VirtualSMC, where are ？If you are convenient tell me ,please.

看起来FakeSMC和VirtualSMC这俩你都用了，只使用其中一个试试？

**Comment by AldousShou** [comment]
slide=0
