### ISSUE TITLE
无法查看具体进程cpu使用率

### ISSUE THREAD

**Issue by AldousShou** [cheneyveron/clover-x79-e5-2670-gtx650#72]
- **系统版本**: 10.15.6

- **已经采取过而无效的方法**: 
升级所有kext驱动
使用了 [这儿](https://github.com/vit9696/AppleALC) 中最新的AppleALC替换了EFI/Clover/Kexts/Other中的AppleALC.kext，问题依旧。

具体问题：无法查看具体线程的cpu使用率。

**Comment by cheneyveron** [comment]
请使用 “活动监视器”，其中有一个选项卡为"CPU"，里面应该有每个进程的CPU使用率。

可惜，macOS下面没有 `top -H` 指令，所以没办法一目了然的看到线程的占用CPU的情况。可以参考[这里](https://stackoverflow.com/questions/6788274/ios-mac-cpu-usage-for-thread)。
