### ISSUE TITLE
请问，华南金牌 烈焰战神 ATX 主板是否可以使用进阶指南中的2个BIOS呢？就是以下两个。

### ISSUE THREAD

**Issue by luobingwei** [cheneyveron/clover-x79-e5-2670-gtx650#73]
在 **x7947_ORIGIN_MSR_LOGO_NVME.rom** 中：
解锁了 msr 寄存器。
现在你可以直接享受 Apple 原生的电源管理了，包括两档变频（1.2 与 3.0GHz）、睡眠唤醒等，而不需要对系统文件打任何补丁。

通过添加 SSDT ，变频档位增加到了5档，通过CPUFriend注入以后，达到了8档 (1.2 / 1.9 / 2.3 / 2.6 / 3.0 / 3.1 / 3.2 / 3.3) 。

解禁了主板中隐藏的各项设置。

修改开机Logo为Apple。

添加了CsmVideoDxe模块。

这下可以在UEFI界面下默认以1080P输出了。而且没有性能问题：）

添加了NVMe支持。
在 **x7947_CPU_RAM_MSR_DSDT_LOGO_NVME.rom** 中：
包含以上全部更改。并且还：

替换了 DSDT 表，修复了 AppleACPIPlatform _isspace panic 与 USB.

具体就是，重命名EUSB -> EH01，USBE -> EH02，删除了包含CUU0-3的四行。

解除了内存和处理器频率限制。

**Comment by cheneyveron** [comment]
查看一下pcie槽上面有写2.45/2.46/2.47这种版本号吗？如果有，那么可以。否则不行。
如果不确定的话，建议不要刷噢。

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: luobingwei <notifications@github.com>
发送时间: Sunday, October 11, 2020 7:00:46 PM
收件人: cheneyveron/clover-x79-e5-2670-gtx650 <clover-x79-e5-2670-gtx650@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: [cheneyveron/clover-x79-e5-2670-gtx650] 请问，华南金牌 烈焰战神 ATX 主板是否可以使用进阶指南中的2个BIOS呢？就是以下两个。 (#73)


在 x7947_ORIGIN_MSR_LOGO_NVME.rom 中：
解锁了 msr 寄存器。
现在你可以直接享受 Apple 原生的电源管理了，包括两档变频（1.2 与 3.0GHz）、睡眠唤醒等，而不需要对系统文件打任何补丁。

通过添加 SSDT ，变频档位增加到了5档，通过CPUFriend注入以后，达到了8档 (1.2 / 1.9 / 2.3 / 2.6 / 3.0 / 3.1 / 3.2 / 3.3) 。

解禁了主板中隐藏的各项设置。

修改开机Logo为Apple。

添加了CsmVideoDxe模块。

这下可以在UEFI界面下默认以1080P输出了。而且没有性能问题：）

添加了NVMe支持。
在 x7947_CPU_RAM_MSR_DSDT_LOGO_NVME.rom 中：
包含以上全部更改。并且还：

替换了 DSDT 表，修复了 AppleACPIPlatform _isspace panic 与 USB.

具体就是，重命名EUSB -> EH01，USBE -> EH02，删除了包含CUU0-3的四行。

解除了内存和处理器频率限制。

―
