### ISSUE TITLE
目前有对Big Sur的支持计划吗？

### ISSUE THREAD

**Issue by Yumpoo-Hsu** [cheneyveron/clover-x79-e5-2670-gtx650#74]

**Comment by itq5** [comment]
同求

**Comment by cheneyveron** [comment]
还正在尝试中，不仅打算支持Big Sur，还打算换成OpenCore。朋友们请耐心等待。

Still Trying supporting macOS Big Sur as well as turning to OpenCore. Please be patient.

**Comment by szcxs** [comment]
我的OpenCore已经可以使用真USB3.0，7档变频，电源四项，我的华南2.49P只支能设置S1睡眠，所以也支持了。缺点是依靠精简的DSDT支持，所以OpenCore进windows失败，尝试过DSDT替换成你的配置型补丁，进不去，还在研究中

**Comment by cheneyveron** [comment]
我现在只使用OpenCore引导了Catalina，Big Sur还在琢磨中。 我的微信是 cheneyveron，有兴趣的话欢迎添加交流~

**Comment by xinyangmaojian** [comment]
> 还正在尝试中，不仅打算支持Big Sur，还打算换成OpenCore。朋友们请耐心等待。
> 
> Still Trying supporting macOS Big Sur as well as turning to OpenCore. Please be patient.

加油大佬   白嫖党表示强烈支持并耐心的坐等白嫖。

**Comment by SkyMonkya** [comment]
OC 2689 能正常玩就是变频有问题😭
