### ISSUE TITLE
请问你是如何讲原始bios中的cfg移除的？

### ISSUE THREAD

**Issue by Yumpoo-Hsu** [cheneyveron/clover-x79-e5-2670-gtx650#79]
我刷你提供的bios会遇到紫屏卡appleacpicpu等问题，排查了lilu，oc和ssdt一圈下来没有找出来原因，所以想仅修改自己的bios的cfg来进行进一步排查，但是使用了uefitool、mmtool都没有找到相应的模块

**Comment by cheneyveron** [comment]
https://www.itmanbu.com/ami-bios-modification.html
