### ISSUE TITLE
maxdos iso版的实在是找不到。

### ISSUE THREAD

**Issue by WaterWei** [cheneyveron/clover-x79-e5-2670-gtx650#8]
能否帮忙提供一下呢？

**Comment by cheneyveron** [comment]
请使用谷歌搜索 MaxDos ，第一个就是官网了：
http://pzz.cn/forum.php?mod=viewthread&tid=122806
然后这个页面上有个官方下载地址：
http://pzz.cn/soft/maxdos93.zip
我猜你还会问我FPT(aka Intel Flash Programming Tool)在哪里下载：
https://overclocking.guide/download/flash-programming-tool/
另外，**刷前请务必先买个USB编程器。否则成砖以后无解。**
